### PR TITLE
Revert 0.1.23 - 0.1.24 changes

### PR DESCRIPTION
**Pull request by samselikoff**
The umd build was broken in 0.1.23, but the package worked with our gatsby site. Something [between 0.1.23 and 0.1.24](https://github.com/miragejs/server/compare/v0.1.23...v0.1.24) broke our Gatsby site, but for the life of me I couldn't figure it out.

I think umd might be not working but I'm reverting all changes from 0.1.23 – 0.1.24 since 0.1.23 seems to work on most projects. We can revisit soon.

### CODE REVIEW

**Comment by stukalin** [comment]
@samselikoff And again it broke the ie11 support :-(

**Comment by samselikoff** [comment]
I think we're closer to a solution.

Question – you're working on an Ember app right?

**Comment by stukalin** [comment]
@samselikoff yes, I am

**Comment by stukalin** [comment]
@samselikoff any news re IE11?

**Comment by samselikoff** [comment]
I think we have a lot of our build issues fixed, so my next step was going to be to try it with a new ember app that targets ie 11.

Do use the targets feature of ember cli?

**Comment by stukalin** [comment]
@samselikoff yes, we do

**Comment by samselikoff** [comment]
@stukalin sorry for the delay on this.

I just tried a brand new Ember app, added `ie 11` to my `config/targets.js`, and installed Mirage. It didn't work at first, but then I went to `ember-cli-build.js` and added the polyfill

```
  let app = new EmberApp(defaults, {
    'ember-cli-babel': {
      includePolyfill: true
    }
  });
```

and now I have a passing test & development is working as well.

Do you have `ie 11` in your config/targets _and_ have the polyfill enabled?

**Comment by stukalin** [comment]
@samselikoff yeah, the latest Ember has included this one in their templates and now it works for us as well. Sorry for disturbing you :-D

**Comment by samselikoff** [comment]
Oh no problem! Glad it all worked & was good for me to learn a bit more about this too 😄

**Pull request merged**
