### PR TITLE
Fix ActiveModelSerializer bug with polymorphic relationship

### PR DESCRIPTION
**Pull request by samselikoff**

### CODE REVIEW

**Comment by Turbo87** [comment]
awesome, thanks. can you let me know once it's published?

**Comment by samselikoff** [comment]
Travis building v1.1.13 now!

https://github.com/samselikoff/ember-cli-mirage/releases/tag/v1.1.3

**Comment by samselikoff** [comment]
@Turbo87 published

**Comment by Turbo87** [comment]
awesome, thanks! ❤️

**Pull request merged**
