### PR TITLE
Rollback polyfills for ie11

### PR DESCRIPTION
**Pull request by stukalin**
Addresses #63

It looks like the commit dda5f85637fe41d6202c894ce377c5bacf87c324 has rolled back the changes were made in the #54 so that the latest version of the server lacks the support of IE11 again (that was close). I've just checked locally that bringing those polyfills back fixes things for ie 11.

### CODE REVIEW

**Comment by samselikoff** [comment]
@stukalin oh man. Apologies! We are actually working over in #107 to get tests in place that cover our builds so this doesn't happen again.

Sorry about that, will address this soon 👍

**Comment by samselikoff** [comment]
I *believe* the latest way to do this is with the `useBuiltIns` option to `@babel/preset-env`, which [we are doing here for our umd build](https://github.com/miragejs/server/blob/master/rollup.config.js#L95-L98). The problem is we fixed a typo to our esm build, so I'm guessing your setup started pulling it in, but [we didn't make the change to the babel plugin over there](https://github.com/miragejs/server/blob/master/rollup.config.js#L20) after removing the import statement version.

Let me try that change and we'll see if it works for you. (I don't want to block this on test coverage because it's quite hard and could take longer.)

**Comment by samselikoff** [comment]
I think we'll need to publish to npm so you can try it out due to the build. I'll publish a beta and let you know when it's ready.

**Comment by samselikoff** [comment]
@stukalin could you give `v0.1.24-beta.1` a try?

**Comment by stukalin** [comment]
I will try it in 8 days, for my vacation has just started.

пт, 6 сент. 2019 г., 17:34 Sam Selikoff <notifications@github.com>:

**Comment by samselikoff** [comment]
Sounds good! Let me know then if you run into any issues.

**Pull request closed without merging**
